import React, { useState } from 'react';
import { useStrategy } from '../../context/StrategyContext.jsx';
import { DecisionBadge } from '../common/DecisionBadge.jsx';
import { DECISIONS } from '../../engine/decisionEngine.js';
import { ROADMAP_PHASES } from '../../engine/roadmapEngine.js';
import { AlertTriangle, ArrowDown, ArrowRight, CheckCircle2, ChevronDown, GitBranch, Printer, ShieldCheck } from 'lucide-react';

function DetailList({ label, values, tone = 'slate' }) {
  const color = tone === 'emerald' ? 'text-emerald-300' : tone === 'amber' ? 'text-amber-300' : 'text-slate-300';
  return <div><div className="text-[10px] uppercase tracking-wider text-slate-500 mb-1">{label}</div><ul className="space-y-1">{(Array.isArray(values) ? values : [values]).filter(Boolean).map((value, index) => <li key={index} className={`text-[11px] leading-relaxed ${color} flex gap-1.5`}><span className="text-slate-600">•</span><span>{value}</span></li>)}</ul></div>;
}

function RoadmapItem({ item }) {
  const [expanded, setExpanded] = useState(false);
  return <article className="border border-slate-800 bg-slate-950/70 rounded-lg overflow-hidden"><button type="button" onClick={() => setExpanded((value) => !value)} className="w-full text-left p-3 hover:bg-slate-900 transition-colors cursor-pointer"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="text-xs font-bold text-white truncate">{item.componentName}</h3><p className="text-[11px] text-slate-400 mt-1 line-clamp-2">{item.milestones?.[0] || item.objective}</p></div><div className="flex items-center gap-1.5 shrink-0"><DecisionBadge decision={item.decision} size="sm" /><ChevronDown className={`w-3.5 h-3.5 text-slate-500 transition-transform ${expanded ? 'rotate-180' : ''}`} /></div></div></button>{expanded && <div className="border-t border-slate-800 p-3 space-y-3"><DetailList label="Objective" values={item.objective || item.objectives} /><DetailList label="Milestones" values={item.milestones} tone="emerald" /><DetailList label="Dependencies" values={item.dependencies} /><DetailList label="Risk" values={item.risk || item.risks} tone="amber" /><DetailList label="Success criteria" values={item.successCriteria} tone="emerald" />{item.decision === DECISIONS.HYBRID && item.track && <div className="grid grid-cols-1 gap-2 pt-2 border-t border-slate-800"><div><div className="text-[10px] uppercase tracking-wider text-sky-400 mb-1">Partner track</div><p className="text-[11px] text-slate-300 leading-relaxed">{item.track.partner}</p></div><div><div className="text-[10px] uppercase tracking-wider text-emerald-400 mb-1">Internal / owned track</div><p className="text-[11px] text-slate-300 leading-relaxed">{item.track.internal}</p></div></div>}</div>}</article>;
}

export function RoadmapView() {
  const { phasedRoadmap = [], roadmapDependencies = [], roadmapAssumptions = [], activeScenario } = useStrategy();
  const [decisionFilter, setDecisionFilter] = useState('ALL');

  return <div className="space-y-6">
    <header className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 border-b border-slate-800 pb-5"><div><div className="flex items-center gap-2 text-[10px] font-mono uppercase tracking-[0.18em] text-emerald-400 mb-2"><GitBranch className="w-3.5 h-3.5" />Decision-driven execution plan</div><h1 className="text-2xl font-bold tracking-tight text-white">Execution roadmap</h1><p className="text-sm text-slate-400 mt-1 max-w-3xl">Generated from the current BUILD, HYBRID, and PARTNER recommendations for {activeScenario?.name || 'the active strategy'}.</p></div><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 px-3 py-2 text-xs font-semibold text-slate-300 bg-slate-900 border border-slate-700 rounded hover:text-white no-print"><Printer className="w-3.5 h-3.5" />Print roadmap</button></header>

    <div className="flex flex-wrap items-center gap-2 no-print"><span className="text-[11px] text-slate-500 mr-1">Show:</span>{['ALL', DECISIONS.BUILD, DECISIONS.HYBRID, DECISIONS.PARTNER].map((decision) => <button key={decision} type="button" onClick={() => setDecisionFilter(decision)} className={`px-2.5 py-1.5 text-[11px] font-semibold rounded border ${decisionFilter === decision ? 'bg-emerald-950 text-emerald-300 border-emerald-500/40' : 'bg-slate-900 text-slate-400 border-slate-800'}`}>{decision === 'ALL' ? 'All decisions' : decision}</button>)}</div>

    <section className="overflow-x-auto pb-2"><div className="grid grid-cols-4 gap-3 min-w-[1080px]">{ROADMAP_PHASES.map((phase) => { const generated = phasedRoadmap.find((item) => item.id === phase.id); const items = (generated?.items || []).filter((item) => decisionFilter === 'ALL' || item.decision === decisionFilter); return <div key={phase.id} className="min-h-[360px]"><div className="border-b-2 border-emerald-500/40 pb-3 mb-3"><div className="text-[10px] font-mono uppercase tracking-wider text-emerald-400">{phase.timeframe}</div><h2 className="text-sm font-bold text-white mt-1">{phase.title}</h2><p className="text-[11px] text-slate-500 mt-1">{phase.label}</p></div><div className="space-y-2">{items.length > 0 ? items.map((item) => <RoadmapItem key={`${phase.id}-${item.componentId}`} item={item} />) : <div className="p-3 border border-dashed border-slate-800 rounded text-[11px] text-slate-600">No recommendations in this phase.</div>}</div></div>; })}</div></section>

    <section className="bg-slate-900/70 border border-slate-800 rounded-lg p-5"><div className="flex items-center gap-2 mb-4"><GitBranch className="w-4 h-4 text-emerald-400" /><div><h2 className="text-sm font-bold text-white">Dependency flow</h2><p className="text-xs text-slate-500 mt-1">Decision-aware sequencing from partner readiness through owned capability optimization.</p></div></div><div className="flex flex-col md:flex-row md:items-stretch gap-2">{roadmapDependencies.map((stage, index) => <React.Fragment key={stage.label}><div className="flex-1 p-3 bg-slate-950/70 border border-slate-800 rounded"><div className="text-[10px] uppercase tracking-wider text-emerald-400 mb-2">{stage.label}</div><div className="space-y-1">{stage.items.map((item) => <div key={item} className="text-xs text-slate-300">{item}</div>)}</div></div>{index < roadmapDependencies.length - 1 && <ArrowRight className="hidden md:block w-4 h-4 text-slate-600 self-center" />}{index < roadmapDependencies.length - 1 && <ArrowDown className="md:hidden w-4 h-4 text-slate-600 self-center" />}</React.Fragment>)}</div></section>

    <section className="bg-amber-950/20 border border-amber-500/20 rounded-lg p-5"><div className="flex items-center gap-2 mb-3"><ShieldCheck className="w-4 h-4 text-amber-400" /><div><h2 className="text-sm font-bold text-white">Roadmap assumptions</h2><p className="text-[10px] text-amber-300/80 mt-0.5">Performance and throughput figures are illustrative planning targets unless measured and validated.</p></div></div><ul className="space-y-2">{roadmapAssumptions.map((assumption) => <li key={assumption} className="flex items-start gap-2 text-xs text-slate-300"><CheckCircle2 className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />{assumption}</li>)}<li className="flex items-start gap-2 text-xs text-amber-300"><AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />Validate sequencing, capacity, regulatory obligations, and vendor commitments with engineering, compliance, finance, and operations teams.</li></ul></section>
  </div>;
}